title: Wardley Maps - Audiobook
description: >- # this means to ignore newlines until "baseurl:"
  This is a community project that releases Simon Wardley's book "Wardley Maps" as audiobook (generated via Amazon Polly's voice "Brian"). Courtesy of Simon Wardley, Creative Commons Attribution-ShareAlike 4.0.


baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://feststelltaste.github.io/wardley-maps-audiobook"

theme: minima
markdown: kramdown